import { pgTable, text, decimal, timestamp, boolean, integer } from "drizzle-orm/pg-core";
import { user } from "./better-auth";
import { client } from "./client";
import { contract } from "./contract";
import { property } from "./property";
import { servicio } from "./servicio";
import { agency } from "./agency";

export const tenantLedger = pgTable("tenant_ledger", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),

  agencyId: text("agencyId")
    .notNull()
    .references(() => agency.id, { onDelete: "cascade" }),

  contratoId: text("contratoId")
    .notNull()
    .references(() => contract.id, { onDelete: "restrict" }),
  inquilinoId: text("inquilinoId")
    .notNull()
    .references(() => client.id, { onDelete: "restrict" }),
  propietarioId: text("propietarioId")
    .notNull()
    .references(() => client.id, { onDelete: "restrict" }),
  propiedadId: text("propiedadId")
    .notNull()
    .references(() => property.id, { onDelete: "restrict" }),

  // "YYYY-MM" — null for non-periodic items like deposits
  period: text("period"),
  // "YYYY-MM-DD" — due date
  dueDate: text("dueDate"),

  tipo: text("tipo").notNull(),
  // "alquiler" | "servicio" | "bonificacion" | "descuento" | "gasto"
  // | "punitorio" | "deposito" | "ajuste_indice"

  descripcion: text("descripcion").notNull(),

  // null = amount not yet determined (post-adjustment or variable service)
  monto: decimal("monto", { precision: 15, scale: 2 }),
  montoOriginal: decimal("montoOriginal", { precision: 15, scale: 2 }),
  montoManual: decimal("montoManual", { precision: 15, scale: 2 }),

  // Pago parcial — acumulado cobrado. null si nunca hubo pago parcial.
  montoPagado: decimal("montoPagado", { precision: 15, scale: 2 }),

  // Fecha del último pago parcial (YYYY-MM-DD, solo almacenamiento).
  // Es el nuevo "día 0" para calcular punitorios sobre el saldo restante.
  ultimoPagoAt: text("ultimoPagoAt"),

  // Accounting flags
  impactaPropietario: boolean("impactaPropietario").notNull().default(true),
  incluirEnBaseComision: boolean("incluirEnBaseComision").notNull().default(true),
  impactaCaja: boolean("impactaCaja").notNull().default(false),

  // "proyectado" | "pendiente_revision" | "pendiente" | "registrado" | "conciliado" | "cancelado" | "pago_parcial"
  estado: text("estado").notNull().default("proyectado"),
  cancellationReason: text("cancellationReason"),

  reciboNumero: text("reciboNumero"),
  reciboEmitidoAt: timestamp("reciboEmitidoAt"),

  conciliadoAt: timestamp("conciliadoAt"),
  conciliadoPor: text("conciliadoPor").references(() => user.id, { onDelete: "set null" }),

  // Self-reference for installments — plain text, no FK to avoid Drizzle circular reference
  installmentOf: text("installmentOf"),
  installmentNumber: integer("installmentNumber"),
  installmentTotal: integer("installmentTotal"),

  servicioId: text("servicioId").references(() => servicio.id, { onDelete: "set null" }),

  // Link to cash_movement created when impactaCaja=true and item is confirmed
  // FK goes one-way only: caja.ts → tenant_ledger. This field is the reverse pointer.
  // Declared as text to avoid circular import (caja.ts imports tenant-ledger.ts indirectly).
  cajaMovimientoId: text("cajaMovimientoId"),

  isAutoGenerated: boolean("isAutoGenerated").notNull().default(false),

  // Split-payment modality
  // "propietario" | "administracion" | "split" | null (null = no es contrato split)
  beneficiario: text("beneficiario"),
  // JSON guardado al conciliar: { propietario: number, administracion: number }
  splitBreakdown: text("splitBreakdown"),

  createdBy: text("createdBy").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
});

export type TenantLedger = typeof tenantLedger.$inferSelect;
export type NewTenantLedger = typeof tenantLedger.$inferInsert;
