import { NextRequest, NextResponse } from "next/server";
import { headers } from "next/headers";
import { db } from "@/db";
import { tenantLedger } from "@/db/schema/tenant-ledger";
import { contract } from "@/db/schema/contract";
import { contractParticipant } from "@/db/schema/contract-participant";
import { client } from "@/db/schema/client";
import { auth } from "@/lib/auth";
import { canManageClients } from "@/lib/permissions";
import { requireAgencyId, requireAgencyResource, handleAgencyError } from "@/lib/auth/agency";
import { defaultFlagsForTipo } from "@/lib/ledger/flags";
import { and, eq } from "drizzle-orm";
import { z } from "zod";

const createEntrySchema = z.object({
  contratoId: z.string().min(1),
  propietarioId: z.string().min(1),
  propiedadId: z.string().min(1),
  period: z.string().regex(/^\d{4}-\d{2}$/).optional(),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  tipo: z.enum(["alquiler", "servicio", "bonificacion", "descuento", "gasto", "punitorio", "deposito", "ajuste_indice"]),
  descripcion: z.string().min(1),
  monto: z.number().positive().optional(),
  impactaPropietario: z.boolean().optional(),
  incluirEnBaseComision: z.boolean().optional(),
  impactaCaja: z.boolean().optional(),
  installmentOf: z.string().optional(),
  installmentNumber: z.number().int().positive().optional(),
  installmentTotal: z.number().int().positive().optional(),
  servicioId: z.string().optional(),
  beneficiario: z.enum(["propietario", "administracion", "split"]).optional(),
});

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    const agencyId = requireAgencyId(session);
    if (!canManageClients(session!.user.role)) return NextResponse.json({ error: "Sin permisos" }, { status: 403 });

    const { id: inquilinoId } = await params;
    const body = await request.json();
    const result = createEntrySchema.safeParse(body);
    if (!result.success) {
      return NextResponse.json({ error: result.error.errors[0].message }, { status: 400 });
    }

    const data = result.data;

    await requireAgencyResource(client, inquilinoId, agencyId);

    // Verify the contract belongs to this tenant and fetch paymentModality in one query
    const [contractRow] = await db
      .select({ id: contract.id, paymentModality: contract.paymentModality })
      .from(contract)
      .innerJoin(contractParticipant, eq(contractParticipant.contractId, contract.id))
      .where(
        and(
          eq(contract.agencyId, agencyId),
          eq(contractParticipant.agencyId, agencyId),
          eq(contract.id, data.contratoId),
          eq(contractParticipant.clientId, inquilinoId),
          eq(contractParticipant.role, "tenant")
        )
      )
      .limit(1);

    if (!contractRow) {
      return NextResponse.json({ error: "Contrato no encontrado para este inquilino" }, { status: 404 });
    }

    const isSplit = contractRow.paymentModality === "split";

    const computedBeneficiario = isSplit
      ? (data.beneficiario ?? (data.tipo === "alquiler" ? "split" : "propietario"))
      : null;

    const defaults = defaultFlagsForTipo(data.tipo);

    const [entry] = await db
      .insert(tenantLedger)
      .values({
        agencyId,
        contratoId: data.contratoId,
        inquilinoId,
        propietarioId: data.propietarioId,
        propiedadId: data.propiedadId,
        period: data.period,
        dueDate: data.dueDate,
        tipo: data.tipo,
        descripcion: data.descripcion,
        monto: data.monto !== undefined ? String(data.monto) : undefined,
        estado: "pendiente",
        impactaPropietario: data.impactaPropietario ?? defaults.impactaPropietario,
        incluirEnBaseComision: data.incluirEnBaseComision ?? defaults.incluirEnBaseComision,
        impactaCaja: data.impactaCaja ?? defaults.impactaCaja,
        installmentOf: data.installmentOf,
        installmentNumber: data.installmentNumber,
        installmentTotal: data.installmentTotal,
        servicioId: data.servicioId,
        beneficiario: computedBeneficiario ?? undefined,
        isAutoGenerated: false,
        createdBy: session!.user.id,
      })
      .returning();

    return NextResponse.json(entry, { status: 201 });
  } catch (error) {
    const resp = handleAgencyError(error);
    if (resp) return resp;
    console.error("Error POST /api/tenants/:id/ledger:", error);
    return NextResponse.json({ error: "Error al crear el ítem" }, { status: 500 });
  }
}
