import { NextRequest, NextResponse } from "next/server";
import { headers } from "next/headers";
import { db } from "@/db";
import { tenantLedger } from "@/db/schema/tenant-ledger";
import { contract } from "@/db/schema/contract";
import { property } from "@/db/schema/property";
import { auth } from "@/lib/auth";
import { canManageClients } from "@/lib/permissions";
import { and, eq, inArray } from "drizzle-orm";
import { computeNetAndCommission, round2 } from "@/lib/owners/commission";
import { cajaMovimiento } from "@/db/schema/caja";

type EnrichedEntry = {
  id: string;
  contratoId: string;
  inquilinoId: string;
  propietarioId: string;
  propiedadId: string;
  period: string | null;
  dueDate: string | null;
  tipo: string;
  descripcion: string;
  monto: string | null;
  estado: string;
  installmentOf: string | null;
  reciboNumero: string | null;
  montoPagado: string | null;
  ultimoPagoAt: string | null;
  cancellationReason: string | null;
  isAutoGenerated: boolean;
  impactaPropietario: boolean;
  incluirEnBaseComision: boolean;
  impactaCaja: boolean;
  beneficiario: string | null;
  splitBreakdown: string | null;
  isSynthetic?: boolean;
  cashMovementId: string | null;
};

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    if (!session?.user) return NextResponse.json({ error: "No autenticado" }, { status: 401 });
    if (!canManageClients(session.user.role)) return NextResponse.json({ error: "Sin permisos" }, { status: 403 });

    const { id: propietarioId } = await params;

    const currentYear = new Date().getFullYear().toString();

    // Fetch entries joined with contract for managementCommissionPct
    const rawRows = await db
      .select({
        entry: tenantLedger,
        managementCommissionPct: contract.managementCommissionPct,
      })
      .from(tenantLedger)
      .innerJoin(contract, eq(tenantLedger.contratoId, contract.id))
      .where(
        and(
          eq(tenantLedger.propietarioId, propietarioId),
          eq(tenantLedger.impactaPropietario, true)
        )
      )
      .orderBy(tenantLedger.period, tenantLedger.tipo);

    // Map ledgerEntryId → cashMovementId (only conciliated rows have one)
    const conciliatedLedgerIds = rawRows
      .filter(({ entry }) => entry.estado === "conciliado" && entry.reciboNumero)
      .map(({ entry }) => entry.id);

    const cashMovementMap = new Map<string, string>();
    if (conciliatedLedgerIds.length > 0) {
      const cashRows = await db
        .select({ id: cajaMovimiento.id, ledgerEntryId: cajaMovimiento.ledgerEntryId })
        .from(cajaMovimiento)
        .where(inArray(cajaMovimiento.ledgerEntryId, conciliatedLedgerIds));
      for (const row of cashRows) {
        if (row.ledgerEntryId) cashMovementMap.set(row.ledgerEntryId, row.id);
      }
    }

    // Fetch unique properties
    const propertyRows = await db
      .selectDistinct({ id: property.id, address: property.address })
      .from(property)
      .innerJoin(tenantLedger, eq(tenantLedger.propiedadId, property.id))
      .where(
        and(
          eq(tenantLedger.propietarioId, propietarioId),
          eq(tenantLedger.impactaPropietario, true)
        )
      );

    // Build enriched entries with synthetic honorarios rows interleaved
    const ledgerEntries: EnrichedEntry[] = [];
    let totalLiquidadoYTD = 0;
    let totalPendiente = 0;

    for (const { entry, managementCommissionPct } of rawRows) {
      const pct = Number(managementCommissionPct ?? 10);
      const { net, commission, effectivePct } = computeNetAndCommission(entry, pct);

      // Add the original entry (gross monto stays as-is)
      ledgerEntries.push({
        ...entry,
        cashMovementId: cashMovementMap.get(entry.id) ?? null,
      });

      // Sum nets for KPIs
      const isCurrentYear = entry.dueDate?.startsWith(currentYear) ?? false;
      if (entry.estado === "conciliado" && isCurrentYear) {
        totalLiquidadoYTD += net;
      } else if (entry.estado === "pendiente" || entry.estado === "registrado") {
        totalPendiente += net;
      }

      // Add synthetic honorarios row when commission > 0
      if (commission > 0) {
        ledgerEntries.push({
          id: `synthetic-honorarios-${entry.id}`,
          contratoId: entry.contratoId,
          inquilinoId: entry.inquilinoId,
          propietarioId: entry.propietarioId,
          propiedadId: entry.propiedadId,
          period: entry.period,
          dueDate: entry.dueDate,
          tipo: "honorarios_admin",
          descripcion: `Honorarios administración (${effectivePct}%)`,
          monto: String(-commission),
          estado: entry.estado,
          installmentOf: null,
          reciboNumero: entry.reciboNumero,
          montoPagado: null,
          ultimoPagoAt: null,
          cancellationReason: null,
          isAutoGenerated: true,
          impactaPropietario: true,
          incluirEnBaseComision: false,
          impactaCaja: false,
          beneficiario: null,
          splitBreakdown: null,
          isSynthetic: true,
          cashMovementId: null,
        });
      }
    }

    return NextResponse.json({
      kpis: {
        totalLiquidadoYTD: round2(totalLiquidadoYTD),
        totalPendiente: round2(totalPendiente),
      },
      ledgerEntries,
      properties: propertyRows,
    });
  } catch (error) {
    console.error("Error GET /api/owners/:id/cuenta-corriente:", error);
    return NextResponse.json({ error: "Error al obtener la cuenta corriente" }, { status: 500 });
  }
}
