"use client";

import { useState, useEffect } from "react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { AlertTriangle } from "lucide-react";
import { type LedgerEntry } from "@/components/tenants/ledger-table";

export type EntryEditData = {
  descripcion?: string;
  monto?: number;
  dueDate?: string;
  period?: string;
  impactaPropietario?: boolean;
  incluirEnBaseComision?: boolean;
  impactaCaja?: boolean;
};

type Props = {
  entry: LedgerEntry | null;
  onOpenChange: (open: boolean) => void;
  onSave: (data: EntryEditData) => Promise<void>;
  isSplitContract?: boolean;
  onBeneficiarioOverride?: (entryId: string, value: string | null) => void;
  readOnly?: boolean;
};

function formatMontoInput(raw: string): string {
  const commaIdx = raw.lastIndexOf(",");
  let intRaw: string;
  let decStr: string | null = null;

  if (commaIdx !== -1) {
    intRaw = raw.slice(0, commaIdx);
    decStr = raw.slice(commaIdx + 1).replace(/[^\d]/g, "").slice(0, 2);
  } else if (raw.endsWith(".")) {
    intRaw = raw.slice(0, -1);
    decStr = "";
  } else {
    intRaw = raw;
  }

  const intClean = intRaw.replace(/[^\d]/g, "");
  const intFormatted = intClean.replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  return decStr !== null ? `${intFormatted},${decStr}` : intFormatted;
}

function formatInitialMonto(raw: string): string {
  const n = parseFloat(raw);
  if (isNaN(n)) return "";
  const parts = n.toFixed(2).split(".");
  const intFormatted = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  return parts[1] === "00" ? intFormatted : `${intFormatted},${parts[1]}`;
}

function formatPeriod(period: string): string {
  const [year, month] = period.split("-");
  return `${month}-${year}`;
}

function formatDueDateDisplay(iso: string): string {
  const [year, month, day] = iso.split("-");
  return `${day}-${month}-${year}`;
}

function parseDueDateDisplay(display: string): string {
  const parts = display.split("-");
  if (parts.length === 3 && parts[2].length === 4) {
    return `${parts[2]}-${parts[1]}-${parts[0]}`;
  }
  return display;
}

function parsePeriodDisplay(display: string): string {
  const parts = display.split("-");
  if (parts.length === 2 && parts[1].length === 4) {
    return `${parts[1]}-${parts[0]}`;
  }
  return display;
}

function formatPeriodInput(raw: string): string {
  const digits = raw.replace(/\D/g, "").slice(0, 6);
  if (digits.length <= 2) return digits;
  return `${digits.slice(0, 2)}-${digits.slice(2)}`;
}

function formatDueDateInput(raw: string): string {
  const digits = raw.replace(/\D/g, "").slice(0, 8);
  if (digits.length <= 2) return digits;
  if (digits.length <= 4) return `${digits.slice(0, 2)}-${digits.slice(2)}`;
  return `${digits.slice(0, 2)}-${digits.slice(2, 4)}-${digits.slice(4)}`;
}

const ESTADO_LABEL: Record<string, string> = {
  proyectado:          "Proyectado",
  pendiente:           "Pendiente",
  pendiente_revision:  "Revisar",
  registrado:          "Registrado",
  conciliado:          "Pagado",
  cancelado:           "Cancelado",
  pago_parcial:        "Pago parcial",
};

export function EntryDetailDialog({ entry, onOpenChange, onSave, isSplitContract = false, onBeneficiarioOverride, readOnly = false }: Props) {
  const [descripcion, setDescripcion] = useState("");
  const [monto, setMonto] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [impactaPropietario, setImpactaPropietario] = useState(true);
  const [incluirEnBaseComision, setIncluirEnBaseComision] = useState(true);
  const [period, setPeriod] = useState("");
  const [impactaCaja, setImpactaCaja] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [beneficiarioOverride, setBeneficiarioOverride] = useState<string | null>(null);

  useEffect(() => {
    if (entry) {
      setDescripcion(entry.descripcion);
      setMonto(entry.monto ? formatInitialMonto(entry.monto) : "");
      setPeriod(entry.period ? formatPeriod(entry.period) : "");
      setDueDate(entry.dueDate ? formatDueDateDisplay(entry.dueDate) : "");
      setImpactaPropietario(entry.impactaPropietario);
      setIncluirEnBaseComision(entry.incluirEnBaseComision);
      setImpactaCaja(entry.impactaCaja);
      setError(null);
      setSaving(false);
      setBeneficiarioOverride(null);
    }
  }, [entry]);

  const isEditable = !readOnly && entry !== null && !entry.isAutoGenerated && entry.estado !== "conciliado" && entry.estado !== "cancelado";

  async function handleSave() {
    if (!entry) return;
    const montoNum = parseFloat(monto.replace(/\./g, "").replace(",", "."));
    if (isNaN(montoNum) || montoNum <= 0) { setError("El monto debe ser un número positivo"); return; }
    if (!descripcion.trim()) { setError("La descripción es obligatoria"); return; }
    setSaving(true);
    setError(null);
    try {
      await onSave({
        descripcion: descripcion.trim(),
        monto: montoNum,
        ...(dueDate ? { dueDate: parseDueDateDisplay(dueDate) } : {}),
        ...(period ? { period: parsePeriodDisplay(period) } : {}),
        impactaPropietario,
        incluirEnBaseComision,
        impactaCaja,
      });
      onOpenChange(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Error al guardar");
      setSaving(false);
    }
  }

  return (
    <Dialog open={entry !== null} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>Detalle del movimiento</DialogTitle>
        </DialogHeader>
        {entry && (
          <div className="space-y-3 text-sm">
            <div className="flex items-center gap-2 flex-wrap">
              <Badge variant="outline" className="text-xs capitalize">{entry.tipo}</Badge>
              <Badge variant="outline" className="text-xs">
                {ESTADO_LABEL[entry.estado] ?? entry.estado}
              </Badge>
              {entry.period && (
                <span className="text-xs text-muted-foreground">{entry.period}</span>
              )}
            </div>

            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Descripción</Label>
              <Input
                value={descripcion}
                onChange={(e) => setDescripcion(e.target.value)}
                className="h-9"
                disabled={!isEditable}
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Monto ($)</Label>
              <Input
                value={monto}
                onChange={(e) => setMonto(formatMontoInput(e.target.value))}
                type="text"
                inputMode="decimal"
                className="h-9"
                disabled={!isEditable}
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Fecha de período</Label>
              <Input
                value={period}
                onChange={(e) => setPeriod(formatPeriodInput(e.target.value))}
                placeholder="MM-YYYY"
                className="h-9"
                disabled={!isEditable}
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Fecha de vencimiento</Label>
              <Input
                value={dueDate}
                onChange={(e) => setDueDate(formatDueDateInput(e.target.value))}
                placeholder="DD-MM-YYYY"
                className="h-9"
                disabled={!isEditable}
              />
            </div>

            <div className="border-t border-border pt-3 space-y-2.5">
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Contabilidad</p>
              <div className="flex items-center justify-between">
                <Label htmlFor="d-flag-propietario" className="text-xs font-normal">
                  Impacta liquidación del propietario
                </Label>
                <Switch
                  id="d-flag-propietario"
                  checked={impactaPropietario}
                  onCheckedChange={setImpactaPropietario}
                  disabled={!isEditable}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="d-flag-comision" className="text-xs font-normal">
                  Incluir en base de honorarios
                </Label>
                <Switch
                  id="d-flag-comision"
                  checked={incluirEnBaseComision}
                  onCheckedChange={setIncluirEnBaseComision}
                  disabled={!isEditable}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="d-flag-caja" className="text-xs font-normal">
                  Impacta caja
                </Label>
                <Switch
                  id="d-flag-caja"
                  checked={impactaCaja}
                  onCheckedChange={setImpactaCaja}
                  disabled={!isEditable}
                />
              </div>
            </div>

            {isSplitContract && (
              <div className="border-t border-border pt-3 space-y-2">
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Destino del cobro</p>
                <Select
                  value={beneficiarioOverride ?? entry.beneficiario ?? "split"}
                  onValueChange={(v) => {
                    const isChanged = v !== (entry.beneficiario ?? "split");
                    const newVal = isChanged ? v : null;
                    setBeneficiarioOverride(newVal);
                    onBeneficiarioOverride?.(entry.id, newVal);
                  }}
                >
                  <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="split">Split (propietario + administración)</SelectItem>
                    <SelectItem value="propietario">↗ Todo al propietario</SelectItem>
                    <SelectItem value="administracion">↗ Todo a la administración</SelectItem>
                  </SelectContent>
                </Select>
                {beneficiarioOverride !== null && (
                  <Alert className="border-amber-700/50 bg-amber-950/30 py-2">
                    <AlertTriangle className="size-3 text-amber-400" />
                    <AlertDescription className="text-xs text-amber-400">
                      Estás cambiando el destino original de este ítem. Esto afecta el desglose del recibo.
                      El cambio aplica solo para este cobro y no queda guardado en el ítem.
                    </AlertDescription>
                  </Alert>
                )}
              </div>
            )}

            {!isEditable && entry.estado !== "conciliado" && entry.estado !== "cancelado" && (
              <p className="text-xs text-muted-foreground italic">
                Este movimiento fue generado automáticamente y no puede editarse.
              </p>
            )}
            {error && <p className="text-xs text-destructive">{error}</p>}
          </div>
        )}
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
            Cerrar
          </Button>
          {isEditable && (
            <Button onClick={handleSave} disabled={saving}>
              {saving ? "Guardando..." : "Guardar"}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
