"use client";

import { useState, useEffect } from "react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { type LedgerEntry } from "@/components/tenants/ledger-table";

export type EntryEditData = {
  descripcion?: string;
  monto?: number;
  dueDate?: string;
  impactaPropietario?: boolean;
  incluirEnBaseComision?: boolean;
  impactaCaja?: boolean;
};

type Props = {
  entry: LedgerEntry | null;
  onOpenChange: (open: boolean) => void;
  onSave: (data: EntryEditData) => Promise<void>;
};

const ESTADO_LABEL: Record<string, string> = {
  proyectado:          "Proyectado",
  pendiente:           "Pendiente",
  pendiente_revision:  "Revisar",
  registrado:          "Registrado",
  conciliado:          "Pagado",
  cancelado:           "Cancelado",
  pago_parcial:        "Pago parcial",
};

export function EntryDetailDialog({ entry, onOpenChange, onSave }: Props) {
  const [descripcion, setDescripcion] = useState("");
  const [monto, setMonto] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [impactaPropietario, setImpactaPropietario] = useState(true);
  const [incluirEnBaseComision, setIncluirEnBaseComision] = useState(true);
  const [impactaCaja, setImpactaCaja] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (entry) {
      setDescripcion(entry.descripcion);
      setMonto(entry.monto ? String(parseFloat(entry.monto)) : "");
      setDueDate(entry.dueDate ?? "");
      setImpactaPropietario(entry.impactaPropietario);
      setIncluirEnBaseComision(entry.incluirEnBaseComision);
      setImpactaCaja(entry.impactaCaja);
      setError(null);
      setSaving(false);
    }
  }, [entry]);

  const isEditable = entry !== null && !entry.isAutoGenerated && entry.estado !== "conciliado" && entry.estado !== "cancelado";

  async function handleSave() {
    if (!entry) return;
    const montoNum = parseFloat(monto.replace(/\./g, "").replace(",", "."));
    if (isNaN(montoNum) || montoNum <= 0) { setError("El monto debe ser un número positivo"); return; }
    if (!descripcion.trim()) { setError("La descripción es obligatoria"); return; }
    setSaving(true);
    setError(null);
    try {
      await onSave({
        descripcion: descripcion.trim(),
        monto: montoNum,
        ...(dueDate ? { dueDate } : {}),
        impactaPropietario,
        incluirEnBaseComision,
        impactaCaja,
      });
      onOpenChange(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Error al guardar");
      setSaving(false);
    }
  }

  return (
    <Dialog open={entry !== null} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>Detalle del movimiento</DialogTitle>
        </DialogHeader>
        {entry && (
          <div className="space-y-3 text-sm">
            <div className="flex items-center gap-2 flex-wrap">
              <Badge variant="outline" className="text-xs capitalize">{entry.tipo}</Badge>
              <Badge variant="outline" className="text-xs">
                {ESTADO_LABEL[entry.estado] ?? entry.estado}
              </Badge>
              {entry.period && (
                <span className="text-xs text-muted-foreground">{entry.period}</span>
              )}
            </div>

            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Descripción</Label>
              <Input
                value={descripcion}
                onChange={(e) => setDescripcion(e.target.value)}
                className="h-9"
                disabled={!isEditable}
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Monto ($)</Label>
              <Input
                value={monto}
                onChange={(e) => setMonto(e.target.value)}
                type="text"
                inputMode="decimal"
                className="h-9"
                disabled={!isEditable}
              />
            </div>
            <div className="space-y-1">
              <Label className="text-xs text-muted-foreground">Fecha de vencimiento</Label>
              <Input
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                placeholder="YYYY-MM-DD"
                className="h-9"
                disabled={!isEditable}
              />
            </div>

            <div className="border-t border-border pt-3 space-y-2.5">
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Contabilidad</p>
              <div className="flex items-center justify-between">
                <Label htmlFor="d-flag-propietario" className="text-xs font-normal">
                  Impacta liquidación del propietario
                </Label>
                <Switch
                  id="d-flag-propietario"
                  checked={impactaPropietario}
                  onCheckedChange={setImpactaPropietario}
                  disabled={!isEditable}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="d-flag-comision" className="text-xs font-normal">
                  Incluir en base de honorarios
                </Label>
                <Switch
                  id="d-flag-comision"
                  checked={incluirEnBaseComision}
                  onCheckedChange={setIncluirEnBaseComision}
                  disabled={!isEditable}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="d-flag-caja" className="text-xs font-normal">
                  Impacta caja
                </Label>
                <Switch
                  id="d-flag-caja"
                  checked={impactaCaja}
                  onCheckedChange={setImpactaCaja}
                  disabled={!isEditable}
                />
              </div>
            </div>

            {!isEditable && entry.estado !== "conciliado" && entry.estado !== "cancelado" && (
              <p className="text-xs text-muted-foreground italic">
                Este movimiento fue generado automáticamente y no puede editarse.
              </p>
            )}
            {error && <p className="text-xs text-destructive">{error}</p>}
          </div>
        )}
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
            Cerrar
          </Button>
          {isEditable && (
            <Button onClick={handleSave} disabled={saving}>
              {saving ? "Guardando..." : "Guardar"}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
