import { NextRequest, NextResponse } from "next/server";
import { headers } from "next/headers";
import { db } from "@/db";
import { tenantLedger } from "@/db/schema/tenant-ledger";
import { auth } from "@/lib/auth";
import { canManageClients } from "@/lib/permissions";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { defaultFlagsForTipo } from "@/lib/ledger/flags";

const punitorioSchema = z.object({
  monto: z.number().positive(),
  descripcion: z.string().min(1),
});

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; entryId: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    if (!session?.user) return NextResponse.json({ error: "No autenticado" }, { status: 401 });
    if (!canManageClients(session.user.role)) return NextResponse.json({ error: "Sin permisos" }, { status: 403 });

    const { id: inquilinoId, entryId } = await params;
    const body = await request.json();
    const result = punitorioSchema.safeParse(body);
    if (!result.success) {
      return NextResponse.json({ error: result.error.errors[0].message }, { status: 400 });
    }

    const [parent] = await db
      .select()
      .from(tenantLedger)
      .where(and(eq(tenantLedger.id, entryId), eq(tenantLedger.inquilinoId, inquilinoId)))
      .limit(1);

    if (!parent) return NextResponse.json({ error: "Ítem padre no encontrado" }, { status: 404 });
    if (parent.tipo !== "alquiler") {
      return NextResponse.json({ error: "Solo se puede agregar punitorio a ítems de alquiler" }, { status: 422 });
    }

    const [punitorioEntry] = await db
      .insert(tenantLedger)
      .values({
        contratoId: parent.contratoId,
        inquilinoId: parent.inquilinoId,
        propietarioId: parent.propietarioId,
        propiedadId: parent.propiedadId,
        period: parent.period ?? undefined,
        dueDate: parent.dueDate ?? undefined,
        tipo: "punitorio",
        descripcion: result.data.descripcion,
        monto: String(result.data.monto),
        estado: "pendiente",
        installmentOf: parent.id,
        isAutoGenerated: false,
        createdBy: session.user.id,
        ...defaultFlagsForTipo("punitorio"),
      })
      .returning();

    return NextResponse.json(punitorioEntry, { status: 201 });
  } catch (error) {
    console.error("Error POST punitorio:", error);
    return NextResponse.json({ error: "Error al agregar punitorio" }, { status: 500 });
  }
}
