import { NextRequest, NextResponse } from "next/server";
import { headers } from "next/headers";
import { db } from "@/db";
import { tenantLedger } from "@/db/schema/tenant-ledger";
import { auth } from "@/lib/auth";
import { canManageClients } from "@/lib/permissions";
import { and, eq, not } from "drizzle-orm";
import { z } from "zod";

const patchSchema = z.object({
  monto: z.number().positive().optional(),
  descripcion: z.string().min(1).optional(),
  estado: z.enum(["pendiente", "registrado", "cancelado"]).optional(),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  cancellationReason: z.string().optional(),
  impactaPropietario: z.boolean().optional(),
  incluirEnBaseComision: z.boolean().optional(),
  impactaCaja: z.boolean().optional(),
});

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; entryId: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    if (!session?.user) return NextResponse.json({ error: "No autenticado" }, { status: 401 });
    if (!canManageClients(session.user.role)) return NextResponse.json({ error: "Sin permisos" }, { status: 403 });

    const { id: inquilinoId, entryId } = await params;
    const body = await request.json();
    const result = patchSchema.safeParse(body);
    if (!result.success) {
      return NextResponse.json({ error: result.error.errors[0].message }, { status: 400 });
    }

    const [existing] = await db
      .select({ estado: tenantLedger.estado, isAutoGenerated: tenantLedger.isAutoGenerated })
      .from(tenantLedger)
      .where(and(eq(tenantLedger.id, entryId), eq(tenantLedger.inquilinoId, inquilinoId)))
      .limit(1);

    if (!existing) return NextResponse.json({ error: "Ítem no encontrado" }, { status: 404 });
    if (existing.estado === "conciliado") {
      return NextResponse.json({ error: "No se puede modificar un ítem conciliado" }, { status: 422 });
    }

    const data = result.data;
    const editingProtectedFields =
      data.monto !== undefined ||
      data.descripcion !== undefined ||
      data.dueDate !== undefined ||
      data.impactaPropietario !== undefined ||
      data.incluirEnBaseComision !== undefined ||
      data.impactaCaja !== undefined;

    if (existing.isAutoGenerated && editingProtectedFields) {
      return NextResponse.json(
        { error: "Los movimientos generados automáticamente no pueden editarse" },
        { status: 422 }
      );
    }

    const updated = await db.transaction(async (tx) => {
      const [row] = await tx
        .update(tenantLedger)
        .set({
          ...(data.monto !== undefined && { monto: String(data.monto) }),
          ...(data.descripcion !== undefined && { descripcion: data.descripcion }),
          ...(data.estado !== undefined && { estado: data.estado }),
          ...(data.dueDate !== undefined && { dueDate: data.dueDate }),
          ...(data.cancellationReason !== undefined && data.estado === "cancelado" && { cancellationReason: data.cancellationReason }),
          ...(data.impactaPropietario !== undefined && { impactaPropietario: data.impactaPropietario }),
          ...(data.incluirEnBaseComision !== undefined && { incluirEnBaseComision: data.incluirEnBaseComision }),
          ...(data.impactaCaja !== undefined && { impactaCaja: data.impactaCaja }),
          updatedAt: new Date(),
        })
        .where(and(eq(tenantLedger.id, entryId), eq(tenantLedger.inquilinoId, inquilinoId)))
        .returning();

      if (data.estado === "cancelado") {
        await tx
          .update(tenantLedger)
          .set({
            estado: "cancelado",
            cancellationReason: data.cancellationReason ?? null,
            updatedAt: new Date(),
          })
          .where(and(eq(tenantLedger.installmentOf, entryId), not(eq(tenantLedger.estado, "conciliado"))));
      }

      return row;
    });

    return NextResponse.json(updated);
  } catch (error) {
    console.error("Error PATCH /api/tenants/:id/ledger/:entryId:", error);
    return NextResponse.json({ error: "Error al actualizar el ítem" }, { status: 500 });
  }
}

export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string; entryId: string }> }
) {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    if (!session?.user) return NextResponse.json({ error: "No autenticado" }, { status: 401 });
    if (!canManageClients(session.user.role)) return NextResponse.json({ error: "Sin permisos" }, { status: 403 });

    const { id: inquilinoId, entryId } = await params;

    const [existing] = await db
      .select({ estado: tenantLedger.estado })
      .from(tenantLedger)
      .where(and(eq(tenantLedger.id, entryId), eq(tenantLedger.inquilinoId, inquilinoId)))
      .limit(1);

    if (!existing) return NextResponse.json({ error: "Ítem no encontrado" }, { status: 404 });
    if (existing.estado === "conciliado") {
      return NextResponse.json({ error: "No se puede eliminar un ítem conciliado" }, { status: 422 });
    }

    const [childEntry] = await db
      .select({ id: tenantLedger.id })
      .from(tenantLedger)
      .where(eq(tenantLedger.installmentOf, entryId))
      .limit(1);

    if (childEntry) {
      return NextResponse.json(
        { error: "No se puede eliminar un ítem con punitorios asociados" },
        { status: 422 }
      );
    }

    await db
      .delete(tenantLedger)
      .where(and(eq(tenantLedger.id, entryId), eq(tenantLedger.inquilinoId, inquilinoId)));

    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error("Error DELETE /api/tenants/:id/ledger/:entryId:", error);
    return NextResponse.json({ error: "Error al eliminar el ítem" }, { status: 500 });
  }
}
