"use client";

import { useEffect, useRef } from "react";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { MoreHorizontal } from "lucide-react";
import { cn } from "@/lib/utils";

export type LedgerEntry = {
  id: string;
  contratoId: string;
  propietarioId: string;
  propiedadId: string;
  period: string | null;
  dueDate: string | null;
  tipo: string;
  descripcion: string;
  monto: string | null;
  estado: string;
  installmentOf: string | null;
  reciboNumero: string | null;
  lateInterestPct: string | null;
  montoPagado: string | null;
  ultimoPagoAt: string | null;
  cancellationReason: string | null;
  isAutoGenerated: boolean;
  impactaPropietario: boolean;
  incluirEnBaseComision: boolean;
  impactaCaja: boolean;
  beneficiario: string | null;
  splitBreakdown: string | null;
};

type Props = {
  entries: LedgerEntry[];
  montoOverrides: Record<string, string>;
  selectedIds: Set<string>;
  onToggleSelect: (id: string) => void;
  onSelectMonth: (period: string) => void;
  onDeselectMonth: (period: string) => void;
  onMontoChange: (id: string, value: string) => void;
  onCancelEntry: (entry: LedgerEntry) => void;
  onAnularRecibo: (reciboNumero: string) => void;
  onViewDetail: (entry: LedgerEntry) => void;
  activeFilters: Set<string>;
  isSplitContract?: boolean;
  isOwnerView?: boolean;
  /** Required when isSplitContract is true — omitting defaults to 10% and may show wrong amounts */
  managementCommissionPct?: number;
};

const ESTADO_BADGE: Record<string, { label: string; className: string }> = {
  conciliado:        { label: "Pagado",        className: "bg-income-dim text-income border-income" },
  registrado:        { label: "Registrado",    className: "bg-warning-dim text-warning border-warning" },
  pendiente:         { label: "Pendiente",     className: "bg-primary/10 text-primary border-primary/30" },
  proyectado:        { label: "Proyectado",    className: "bg-transparent text-muted-foreground border-border" },
  pendiente_revision:{ label: "Revisar",       className: "bg-warning-dim text-warning border-warning border-dashed" },
  cancelado:         { label: "Cancelado",     className: "bg-muted text-muted-foreground border-border" },
  pago_parcial:      { label: "Pago parcial",  className: "bg-warning-dim text-warning border-warning" },
};

const PENDING_STATES = ["pendiente", "registrado", "pendiente_revision", "pago_parcial"];

function isSelectable(entry: LedgerEntry): boolean {
  return ["pendiente", "registrado", "pago_parcial"].includes(entry.estado);
}

const CANCELABLE_STATES = ["pendiente", "registrado", "pendiente_revision", "pago_parcial"];

function isCancelable(entry: LedgerEntry): boolean {
  return CANCELABLE_STATES.includes(entry.estado);
}

function isPast(period: string | null): boolean {
  if (!period) return false;
  return period < new Date().toISOString().slice(0, 7);
}

function isCurrent(period: string | null): boolean {
  if (!period) return false;
  return period === new Date().toISOString().slice(0, 7);
}

function isPartialOverride(entry: LedgerEntry, overrides: Record<string, string>): boolean {
  if (entry.tipo === "punitorio") return false;
  if (entry.monto === null) return false;
  const override = overrides[entry.id];
  if (override === undefined) return false;
  const remaining = entry.montoPagado !== null
    ? Math.max(0, Number(entry.monto) - Number(entry.montoPagado))
    : Number(entry.monto);
  return Number(override) < remaining;
}

function formatPeriod(period: string): string {
  const [year, month] = period.split("-");
  return `${month}/${year}`;
}

function formatDescription(desc: string): string {
  return desc.replace(/\b(\d{4})-(\d{2})\b/g, "$2/$1");
}

function groupByPeriod(entries: LedgerEntry[]): Map<string, LedgerEntry[]> {
  const map = new Map<string, LedgerEntry[]>();
  for (const entry of entries) {
    const key = entry.period ?? "__no_period__";
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(entry);
  }
  return map;
}

function DestinoBadge({
  beneficiario,
  managementCommissionPct,
  monto,
  splitBreakdown,
  isOwnerView,
}: {
  beneficiario: string | null;
  managementCommissionPct: number;
  monto: number;
  splitBreakdown: string | null;
  isOwnerView?: boolean;
}) {
  if (isOwnerView && splitBreakdown) {
    return (
      <span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-md bg-blue-950 border border-blue-800 text-blue-300 font-medium">
        ↗ Cobro directo desde inquilino
      </span>
    );
  }
  if (!beneficiario) return null;
  if (beneficiario === "split") {
    const adm = Math.round(monto * (managementCommissionPct / 100));
    const prop = monto - adm;
    return (
      <span className="flex flex-wrap gap-1">
        <span className="text-xs px-1.5 py-0.5 rounded bg-emerald-950 border border-emerald-800 text-emerald-300">
          ↗ Prop. ${prop.toLocaleString("es-AR")}
        </span>
        <span className="text-xs px-1.5 py-0.5 rounded bg-blue-950 border border-blue-800 text-blue-300">
          ↗ Adm. ${adm.toLocaleString("es-AR")}
        </span>
      </span>
    );
  }
  if (beneficiario === "propietario") {
    return (
      <span className="text-xs px-1.5 py-0.5 rounded bg-emerald-950 border border-emerald-800 text-emerald-300">
        ↗ Propietario
      </span>
    );
  }
  return (
    <span className="text-xs px-1.5 py-0.5 rounded bg-blue-950 border border-blue-800 text-blue-300">
      ↗ Administración
    </span>
  );
}

export function LedgerTable({
  entries,
  montoOverrides,
  selectedIds,
  onToggleSelect,
  onSelectMonth,
  onDeselectMonth,
  onMontoChange,
  onCancelEntry,
  onAnularRecibo,
  onViewDetail,
  activeFilters,
  isSplitContract = false,
  isOwnerView = false,
  managementCommissionPct,
}: Props) {
  const showDestino = isSplitContract || isOwnerView;
  const gridCols = showDestino
    ? "grid-cols-[28px_1fr_80px_110px_110px_150px_90px]"
    : "grid-cols-[28px_1fr_80px_110px_110px_90px]";

  const todayPeriod = new Date().toISOString().slice(0, 7);
  const currentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (currentRef.current) {
      currentRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, []);

  const today = new Date().toISOString().slice(0, 10);

  function matchesFilter(e: LedgerEntry): boolean {
    if (activeFilters.size === 0) return true;
    const isFuture = (e.period ?? "") > todayPeriod;
    const isPendingState = PENDING_STATES.includes(e.estado);
    const isOverdue = !isFuture && isPendingState && e.dueDate !== null && e.dueDate < today;
    const isPending = !isFuture && isPendingState && (e.dueDate === null || e.dueDate >= today);
    if (activeFilters.has("overdue") && isOverdue) return true;
    if (activeFilters.has("pending") && isPending) return true;
    if (activeFilters.has("paid") && e.estado === "conciliado") return true;
    if (activeFilters.has("future") && isFuture) return true;
    return false;
  }

  const filtered = entries.filter(matchesFilter);

  const topLevel = filtered.filter((e) => !e.installmentOf || e.tipo === "punitorio");

  const grouped = groupByPeriod(topLevel);
  const periods = [...grouped.keys()].sort();

  return (
    <div className="w-full">
      {/* Column headers — sticky so they stay visible while scrolling */}
      <div className={cn("sticky top-0 z-10 grid items-center gap-2 px-4 py-1.5 bg-muted/80 backdrop-blur-sm border-b border-border", gridCols)}>
        <div />
        <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">Concepto</span>
        <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">Tipo</span>
        <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider text-right">Monto</span>
        <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider text-center">Estado</span>
        {showDestino && (
          <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider">Destino</span>
        )}
        <div />
      </div>

      {periods.map((period) => {
        const periodEntries = grouped.get(period) ?? [];
        const past = isPast(period === "__no_period__" ? null : period);
        const current = isCurrent(period === "__no_period__" ? null : period);
        const future = !past && !current;
        const hasSelectable = periodEntries.some(isSelectable);
        const selectableIds = periodEntries.filter(isSelectable).map((e) => e.id);
        const isMonthSelected = selectableIds.length > 0 && selectableIds.every((id) => selectedIds.has(id));

        return (
          <div
            key={period}
            ref={current ? currentRef : undefined}
            className={cn(
              "border-b border-border",
              past && "opacity-60",
              future && "opacity-50",
              current && "border-l-2 border-l-primary bg-primary/5"
            )}
          >
            {/* Period header */}
            <div className="flex items-center justify-between px-4 py-2">
              <span className={cn(
                "text-xs font-semibold uppercase tracking-wide",
                current ? "text-primary" : "text-muted-foreground"
              )}>
                {current && "● "}
                {period === "__no_period__" ? "Sin período" : formatPeriod(period)}
                {current && " — hoy"}
              </span>
              {hasSelectable && (
                <Button
                  variant="ghost"
                  size="sm"
                  className={cn(
                    "h-6 text-xs px-2.5 font-medium transition-colors",
                    isMonthSelected
                      ? "bg-primary/15 text-primary hover:bg-primary/10"
                      : "bg-muted text-foreground/70 hover:text-foreground hover:bg-muted/70"
                  )}
                  onClick={() => isMonthSelected ? onDeselectMonth(period) : onSelectMonth(period)}
                >
                  {isMonthSelected ? "Deseleccionar" : "Seleccionar mes"}
                </Button>
              )}
            </div>

            {/* Entries */}
            {periodEntries.map((entry) => {
              const selectable = isSelectable(entry);
              const selected = selectedIds.has(entry.id);
              const isPunitorio = entry.tipo === "punitorio";
              const defaultMonto = entry.estado === "pago_parcial" && entry.montoPagado !== null
                ? String(Math.max(0, Number(entry.monto) - Number(entry.montoPagado)))
                : entry.monto;
              const displayMonto = montoOverrides[entry.id] ?? defaultMonto;
              const badge = ESTADO_BADGE[entry.estado] ?? ESTADO_BADGE.pendiente;

              return (
                <div
                  key={entry.id}
                  onClick={() => selectable && onToggleSelect(entry.id)}
                  className={cn(
                    "grid items-center gap-2 px-4 py-2 text-sm",
                    gridCols,
                    isPunitorio && "pl-10 bg-punitorio-dim border-t border-punitorio/30",
                    selectable && "cursor-pointer hover:bg-muted/40",
                    selected && "bg-primary/10 hover:bg-primary/15",
                    isOwnerView && entry.splitBreakdown ? "bg-blue-950/20" : ""
                  )}
                >
                  {/* Checkbox */}
                  <div>
                    {selectable ? (
                      <Checkbox
                        checked={selected}
                        onCheckedChange={() => onToggleSelect(entry.id)}
                        className={isPunitorio ? "border-punitorio" : "border-muted-foreground/60"}
                      />
                    ) : (
                      <div className="w-4 h-4" />
                    )}
                  </div>

                  {/* Descripcion */}
                  <div>
                    <span className={cn(
                      "truncate",
                      isPunitorio && "text-punitorio italic text-xs",
                      entry.monto === null && "text-warning"
                    )}>
                      {isPunitorio && "↳ "}
                      {formatDescription(entry.descripcion)}
                    </span>
                    {/* Subtext: mutually exclusive — DB pago_parcial info OR live partial-override indicator */}
                    {entry.estado === "pago_parcial" && entry.montoPagado !== null ? (
                      <div className="flex gap-3 mt-0.5">
                        <span className="text-[10px] text-muted-foreground">
                          Original: ${Number(entry.monto ?? 0).toLocaleString("es-AR")}
                        </span>
                        <span className="text-[10px] text-income">
                          Pagado: ${Number(entry.montoPagado).toLocaleString("es-AR")}
                        </span>
                      </div>
                    ) : isPartialOverride(entry, montoOverrides) ? (
                      <div className="flex items-center gap-1.5 mt-1">
                        <span className="text-[10px] font-semibold text-warning">
                          Pago parcial
                        </span>
                        <span className="text-[10px] text-muted-foreground">
                          · Saldo: ${(Number(entry.monto) - Number(montoOverrides[entry.id])).toLocaleString("es-AR")}
                        </span>
                      </div>
                    ) : null}
                  </div>

                  {/* Tipo badge */}
                  <span className="text-xs text-muted-foreground truncate">{entry.tipo}</span>

                  {/* Monto */}
                  <div className="flex items-center gap-1 justify-end" onClick={(e) => e.stopPropagation()}>
                    {entry.monto === null ? (
                      <span className="text-warning font-mono text-xs">$???</span>
                    ) : selected ? (
                      <Input
                        value={displayMonto ?? ""}
                        onChange={(e) => onMontoChange(entry.id, e.target.value)}
                        type="number"
                        min="0"
                        className="h-7 w-24 text-right text-xs font-mono"
                      />
                    ) : (
                      <span className="font-mono text-xs">
                        ${Number(entry.monto).toLocaleString("es-AR")}
                      </span>
                    )}
                  </div>

                  {/* Estado badge */}
                  <div className="flex justify-center">
                    <Badge variant="outline" className={cn("text-xs", badge.className)}>
                      {badge.label}
                    </Badge>
                  </div>

                  {/* Destino */}
                  {showDestino && (
                    <div>
                      <DestinoBadge
                        beneficiario={entry.beneficiario ?? (entry.tipo === "alquiler" ? "split" : "propietario")}
                        managementCommissionPct={managementCommissionPct ?? 10}
                        monto={Number(entry.monto ?? 0)}
                        splitBreakdown={entry.splitBreakdown}
                        isOwnerView={isOwnerView}
                      />
                    </div>
                  )}

                  {/* Actions */}
                  <div className="flex items-center justify-end gap-0.5" onClick={(e) => e.stopPropagation()}>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 w-7 p-0 text-muted-foreground hover:text-foreground"
                          aria-label="Acciones"
                        >
                          <MoreHorizontal size={14} />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={() => onViewDetail(entry)}>
                          Ver detalle
                        </DropdownMenuItem>
                        {isPunitorio && entry.estado !== "conciliado" && (
                          <DropdownMenuItem
                            className="text-destructive focus:text-destructive"
                            onClick={() => onCancelEntry(entry)}
                          >
                            Cancelar punitorio
                          </DropdownMenuItem>
                        )}
                        {!isPunitorio && isCancelable(entry) && (
                          <DropdownMenuItem
                            className="text-destructive focus:text-destructive"
                            onClick={() => onCancelEntry(entry)}
                          >
                            Cancelar movimiento
                          </DropdownMenuItem>
                        )}
                      </DropdownMenuContent>
                    </DropdownMenu>
                    {entry.reciboNumero && (
                      <div className="flex items-center gap-0.5">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => window.open(`/recibos/n/${entry.reciboNumero}`, "_blank", "noopener,noreferrer")}
                          className="h-6 px-1.5 text-[10px] text-muted-foreground hover:text-primary"
                          title={`Ver recibo ${entry.reciboNumero}`}
                        >
                          {entry.reciboNumero}
                        </Button>
                        {["conciliado", "pago_parcial"].includes(entry.estado) && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => onAnularRecibo(entry.reciboNumero!)}
                            aria-label="Anular recibo"
                            className="h-6 w-6 p-0 text-muted-foreground hover:text-destructive"
                            title="Anular recibo"
                          >
                            ✕
                          </Button>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        );
      })}
    </div>
  );
}
