import { db } from "../src/db";
import { tenantCharge } from "../src/db/schema/tenant-charge";
import { tenantLedger } from "../src/db/schema/tenant-ledger";
import { defaultFlagsForTipo } from "../src/lib/ledger/flags";

// Maps tenant_charge.categoria → tenant_ledger.tipo
const CATEGORIA_MAP: Record<string, string> = {
  alquiler: "alquiler",
  dias_ocupados: "bonificacion",
  expensas: "servicio",
  punitorios: "punitorio",
  otros: "gasto",
};

// Maps tenant_charge.estado → tenant_ledger.estado
const ESTADO_MAP: Record<string, string> = {
  pendiente: "pendiente",
  pagado: "conciliado",
  cancelado: "cancelado",
};

async function run() {
  console.log("Starting migration: tenant_charge → tenant_ledger");

  const charges = await db.select().from(tenantCharge);
  console.log(`Found ${charges.length} charges to migrate`);

  let migrated = 0;
  let skipped = 0;

  for (const charge of charges) {
    const tipo = CATEGORIA_MAP[charge.categoria ?? ""] ?? "gasto";
    const estado = ESTADO_MAP[charge.estado ?? ""] ?? "pendiente";

    try {
      await db.insert(tenantLedger).values({
        id: charge.id,
        contratoId: charge.contratoId,
        inquilinoId: charge.inquilinoId,
        propietarioId: charge.propietarioId,
        propiedadId: charge.propiedadId,
        period: charge.period ?? undefined,
        tipo,
        descripcion: charge.descripcion,
        monto: charge.monto ?? undefined,
        estado,
        reciboNumero: charge.reciboNumero ?? undefined,
        isAutoGenerated: false,
        createdBy: charge.createdBy ?? undefined,
        createdAt: charge.createdAt ?? new Date(),
        updatedAt: charge.updatedAt ?? new Date(),
        ...defaultFlagsForTipo(tipo),
      });
      migrated++;
    } catch (err) {
      console.error(`Failed to migrate charge ${charge.id}:`, err);
      skipped++;
    }
  }

  console.log(`Migration complete: ${migrated} migrated, ${skipped} skipped`);
}

run().catch(console.error).finally(() => process.exit(0));
