import { NewTenantLedger } from "@/db/schema/tenant-ledger";
import { defaultFlagsForTipo } from "./flags";

type ContractData = {
  id: string;
  propertyId: string;
  ownerId: string;
  startDate: string;      // "YYYY-MM-DD"
  endDate: string;        // "YYYY-MM-DD"
  ledgerStartDate: string | null;
  monthlyAmount: string;  // decimal string
  paymentDay: number;
  adjustmentIndex: string;
  adjustmentFrequency: number;
};

type ServiceData = {
  id: string;
  tipo: string;
  company: string | null;
  tipoGestion: string;
  propietarioResponsable: boolean;
};

// Returns the "YYYY-MM" string for a given Date
function toPeriod(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

// Returns a due date string "YYYY-MM-DD" for a given period and paymentDay
function toDueDate(period: string, paymentDay: number): string {
  const [y, m] = period.split("-").map(Number);
  const lastDay = new Date(y, m, 0).getDate(); // last day of month
  const day = Math.min(paymentDay, lastDay);
  return `${period}-${String(day).padStart(2, "0")}`;
}

// Returns the date when the NEXT adjustment tramo begins (from today's perspective)
function nextAdjustmentDate(startDate: string, adjustmentFrequency: number): Date {
  const start = new Date(startDate + "T00:00:00");
  const today = new Date();

  const monthsFromStart =
    (today.getFullYear() - start.getFullYear()) * 12 +
    (today.getMonth() - start.getMonth());

  const currentTramoIndex = Math.floor(monthsFromStart / adjustmentFrequency);
  const nextTramoMonths = (currentTramoIndex + 1) * adjustmentFrequency;

  const next = new Date(start);
  next.setMonth(next.getMonth() + nextTramoMonths);
  next.setDate(1); // first of that month
  return next;
}

export function buildLedgerEntries(
  contract: ContractData,
  inquilinoId: string,
  services: ServiceData[],
  agencyId: string,
): NewTenantLedger[] {
  const entries: NewTenantLedger[] = [];
  const today = new Date();
  const todayPeriod = toPeriod(today);

  const noAdjustment =
    contract.adjustmentIndex === "none" ||
    contract.adjustmentIndex === "manual" ||
    contract.adjustmentFrequency <= 0;

  const nextAdj = noAdjustment
    ? null
    : nextAdjustmentDate(contract.startDate, contract.adjustmentFrequency);

  // Iterate month by month from ledgerStartDate (if set) or startDate to endDate
  const start = new Date((contract.ledgerStartDate ?? contract.startDate) + "T00:00:00");
  const end = new Date(contract.endDate + "T00:00:00");

  const cursor = new Date(start.getFullYear(), start.getMonth(), 1);
  const endMonth = new Date(end.getFullYear(), end.getMonth(), 1);

  while (cursor <= endMonth) {
    const period = toPeriod(cursor);
    const dueDate = toDueDate(period, contract.paymentDay);

    // Determine estado and monto for this period
    let estado: string;
    let monto: string | null;

    if (period <= todayPeriod) {
      estado = "pendiente";
      monto = contract.monthlyAmount;
    } else if (noAdjustment || nextAdj === null || cursor < nextAdj) {
      estado = "proyectado";
      monto = contract.monthlyAmount;
    } else {
      estado = "pendiente_revision";
      monto = null;
    }

    // Alquiler entry
    entries.push({
      agencyId,
      contratoId: contract.id,
      inquilinoId,
      propietarioId: contract.ownerId,
      propiedadId: contract.propertyId,
      period,
      dueDate,
      tipo: "alquiler",
      descripcion: `Alquiler ${period.slice(5, 7)}/${period.slice(0, 4)}`,
      monto: monto ?? undefined,
      montoOriginal: monto ?? undefined,
      estado,
      isAutoGenerated: true,
      ...defaultFlagsForTipo("alquiler"),
    });

    // Service entries — only for services where propietarioResponsable=true
    for (const svc of services.filter((s) => s.propietarioResponsable)) {
      const impactaCaja = svc.tipoGestion !== "comprobante";

      entries.push({
        agencyId,
        contratoId: contract.id,
        inquilinoId,
        propietarioId: contract.ownerId,
        propiedadId: contract.propertyId,
        period,
        dueDate,
        tipo: "servicio",
        descripcion: `${svc.company ?? svc.tipo} — ${period}`,
        monto: undefined, // always pending review
        estado: "pendiente_revision",
        servicioId: svc.id,
        isAutoGenerated: true,
        ...defaultFlagsForTipo("servicio"),
        impactaCaja,
      });
    }

    cursor.setMonth(cursor.getMonth() + 1);
  }

  return entries;
}
